import math
a = math.factorial(6)
#print(type(a))
#print (a)
import math as m 
a = m.factorial(5)
#print(a)
from math import atan, factorial
a = factorial(4)
#print(a)
from math import factorial , sin , cos , tan
a = factorial(3)
b = sin(90)
c = cos(90)
d = tan(90)
#print(a , b , c , d)   
import math as m 
a = m.sin(m.radians(30))
b = m.cos(m.radians(60))
c = m.tan(m.radians(45))
#print(a , b , c)
a= m.sqrt(25)
#print(a)
a = m.atan(1)
b = m.asin(1)
c = m.acos(1)
#print(a , b , c)
a = m.sinh(5)
b = m.cosh(8)
c = m.tanh(10)
#print(a , b , c)
a = m.asinh(5)
b = m.acosh(8)
c = m.atanh(0.5)
#print(a , b , c)
a = m.pi 
b = m.e 
c = m.tau 
d = m.inf 
#print(a , b , c , d)
a = m.copysign(5 , -3)
#print(a)
b = m.copysign(30 , -10)
#print(b)
c = m.copysign(-20 , 10)
#print(c)
a = m.ceil(10.4)
#print(a)
a = m.floor(7.2)
#print(a)
a = m.erf(2)
#print(a)
a = m.gamma(3)
print (a)