a = "yosef is THE best meNtor iS THE number One in THE woRld"
b = a.partition("is")
#print(b)
c = a.partition("the")
#print (c)
d = a.rpartition("is")
#print (d)
e = a.find("is")
#print (e)
s = a.rfind("in")
#print(s)
n = a.index("is")
#print (n)
k = a.replace('i','w')
#print (k)
x = a.replace ('best','bad ')
#print (x)
y = a.count('m')
#print(y)
r = a.count ("e")
#print (r)
v = a.capitalize()
#print (v)
m = a.title()
#print (m)
h = a.upper()
#print(h)
g = a.swapcase()
#print (g)
t = a.center(70)
print (t)