a = '123456789'
b = "yosef,the,best,mentor"
#print(a[1:9:2])
#print (a[4:12:2])
#print (a[15:30:2])
#print (a[0:7:3])
#print (a[0:5:9])
#print(a[:7:3])
#print (a[:3:8])
#print(a[::2])
#print (a[-1:4:-1])
#print (a[-3:6:-2])
#print (a[::-1])
#print (a[::-6])
#print (list(a))
#print (list(b))
#print (sorted(list(b)))
#print (sorted(list)(set)("b"))
#print (sorted(set)(b))
#print (set(b))
#print(b.split())
#print (b.split(","))
#print (b.split("e"))
#print(b.splitlines())
print (b.splitlines('e'))